export interface Subsector {
  id: string;
  sector: string;
  name: string;
  street: string;
  tickers: string[];
}
// Curated exploration taxonomy. These streets are not a claim of official GICS sub-industries.
export const subsectors: Subsector[] = [
  {
    id: "software",
    sector: "technology",
    name: "Software",
    street: "Software Avenue",
    tickers: ["MSFT", "ORCL", "CRM", "ADBE", "INTU", "NOW", "PANW", "SNPS", "CDNS", "ADSK"],
  },
  {
    id: "semiconductors",
    sector: "technology",
    name: "Semiconductors",
    street: "Semiconductor Street",
    tickers: ["NVDA", "AVGO", "AMD", "QCOM", "TXN", "AMAT", "LRCX", "KLAC", "ADI", "MRVL", "NXPI"],
  },
  {
    id: "memory",
    sector: "technology",
    name: "Memory",
    street: "Memory Lane",
    tickers: ["MU"],
  },
  {
    id: "hardware",
    sector: "technology",
    name: "Hardware",
    street: "Hardware Row",
    tickers: ["AAPL", "CSCO", "IBM"],
  },
  {
    id: "it-services",
    sector: "technology",
    name: "IT Services",
    street: "Services Mews",
    tickers: ["ACN"],
  },
  {
    id: "banking",
    sector: "financials",
    name: "Banking",
    street: "Bankers Row",
    tickers: ["JPM", "BAC", "WFC", "C"],
  },
  {
    id: "payments",
    sector: "financials",
    name: "Payments",
    street: "Payments Avenue",
    tickers: ["V", "MA", "AXP", "PYPL"],
  },
  {
    id: "capital-markets",
    sector: "financials",
    name: "Capital Markets",
    street: "Exchange Street",
    tickers: ["GS", "MS", "BLK", "SPGI", "BRK.B", "COIN"],
  },
  {
    id: "pharma",
    sector: "healthcare",
    name: "Pharmaceuticals",
    street: "Discovery Lane",
    tickers: ["LLY", "JNJ", "ABBV", "MRK", "AMGN", "PFE", "BMY", "VRTX", "REGN", "GILD"],
  },
  {
    id: "medical-technology",
    sector: "healthcare",
    name: "Medical Technology",
    street: "Medical Way",
    tickers: ["TMO", "ABT", "ISRG", "DHR", "IDXX"],
  },
  {
    id: "health-services",
    sector: "healthcare",
    name: "Health Services",
    street: "Care Street",
    tickers: ["UNH"],
  },
  {
    id: "retail",
    sector: "consumer",
    name: "Retail & E-commerce",
    street: "Commerce Street",
    tickers: ["AMZN", "HD", "LOW", "NKE", "TJX", "ORLY", "LULU"],
  },
  {
    id: "automotive",
    sector: "consumer",
    name: "Automotive",
    street: "Motor Row",
    tickers: ["TSLA"],
  },
  {
    id: "travel-dining",
    sector: "consumer",
    name: "Travel & Dining",
    street: "Hospitality Lane",
    tickers: ["MCD", "BKNG", "SBUX", "CMG", "ABNB", "MAR"],
  },
  {
    id: "internet-media",
    sector: "communications",
    name: "Internet & Media",
    street: "Media Avenue",
    tickers: ["GOOGL", "META", "NFLX", "DIS", "TTWO"],
  },
  {
    id: "telecom",
    sector: "communications",
    name: "Telecommunications",
    street: "Telecom Street",
    tickers: ["TMUS", "VZ", "T", "CMCSA", "CHTR"],
  },
  {
    id: "aerospace",
    sector: "industrials",
    name: "Aerospace & Defense",
    street: "Aviation Way",
    tickers: ["GE", "RTX", "LMT"],
  },
  {
    id: "machinery",
    sector: "industrials",
    name: "Machinery",
    street: "Foundry Street",
    tickers: ["CAT", "HON", "ETN", "DE", "PCAR"],
  },
  {
    id: "commercial-services",
    sector: "industrials",
    name: "Commercial Services",
    street: "Commerce Way",
    tickers: ["CTAS", "FAST"],
  },
  {
    id: "transport-services",
    sector: "industrials",
    name: "Transport & Services",
    street: "Logistics Lane",
    tickers: ["UNP", "UPS", "ADP", "CSX", "ODFL"],
  },
  {
    id: "essentials-retail",
    sector: "staples",
    name: "Essential Retail",
    street: "Market Street",
    tickers: ["WMT", "COST"],
  },
  {
    id: "household-food",
    sector: "staples",
    name: "Food & Household",
    street: "Provision Lane",
    tickers: ["PG", "KO", "PEP", "PM", "MDLZ", "CL", "MNST", "KDP", "KHC"],
  },
  {
    id: "oil-gas",
    sector: "energy",
    name: "Oil & Gas",
    street: "Energy Avenue",
    tickers: ["XOM", "CVX", "COP", "FANG"],
  },
  {
    id: "energy-services",
    sector: "energy",
    name: "Energy Services",
    street: "Refinery Row",
    tickers: ["SLB", "EOG", "MPC"],
  },
  {
    id: "power",
    sector: "utilities",
    name: "Power Generation",
    street: "Power Street",
    tickers: ["NEE", "CEG"],
  },
  {
    id: "grid-utilities",
    sector: "utilities",
    name: "Grid Utilities",
    street: "Utility Lane",
    tickers: ["SO", "DUK", "AEP", "EXC", "XEL"],
  },
  {
    id: "chemicals",
    sector: "materials",
    name: "Chemicals",
    street: "Chemical Street",
    tickers: ["LIN", "SHW", "APD"],
  },
  {
    id: "mining",
    sector: "materials",
    name: "Metals & Mining",
    street: "Mineral Lane",
    tickers: ["FCX", "NEM"],
  },
  {
    id: "commercial-property",
    sector: "realestate",
    name: "Commercial Property",
    street: "Property Row",
    tickers: ["PLD", "WELL", "SPG", "O", "CSGP"],
  },
  {
    id: "digital-property",
    sector: "realestate",
    name: "Digital Infrastructure",
    street: "Infrastructure Mews",
    tickers: ["AMT", "EQIX", "SBAC"],
  },
];
export const subsectorFor = (ticker: string) =>
  subsectors.find((s) => s.tickers.includes(ticker));
